/*
 Navicat Premium Data Transfer

 Source Server         : PostgreSql Local
 Source Server Type    : PostgreSQL
 Source Server Version : 100021
 Source Host           : localhost:5432
 Source Catalog        : dbcrud_flask
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 100021
 File Encoding         : 65001

 Date: 18/11/2022 22:26:16
*/


-- ----------------------------
-- Sequence structure for tblmenus_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."tblmenus_id_seq";
CREATE SEQUENCE "public"."tblmenus_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for tblusers_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."tblusers_id_seq";
CREATE SEQUENCE "public"."tblusers_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Table structure for rel_user_menu
-- ----------------------------
DROP TABLE IF EXISTS "public"."rel_user_menu";
CREATE TABLE "public"."rel_user_menu" (
  "id_user" int4 NOT NULL,
  "id_menu" int4 NOT NULL,
  "created_by" varchar(255) COLLATE "pg_catalog"."default",
  "created_dt" timestamp(6),
  "updated_by" varchar(255) COLLATE "pg_catalog"."default",
  "updated_dt" timestamp(6)
)
;

-- ----------------------------
-- Records of rel_user_menu
-- ----------------------------
INSERT INTO "public"."rel_user_menu" VALUES (1, 1, NULL, NULL, NULL, NULL);
INSERT INTO "public"."rel_user_menu" VALUES (1, 2, NULL, NULL, NULL, NULL);

-- ----------------------------
-- Table structure for tblmenus
-- ----------------------------
DROP TABLE IF EXISTS "public"."tblmenus";
CREATE TABLE "public"."tblmenus" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "name" varchar(255) COLLATE "pg_catalog"."default",
  "parent_id" int4,
  "sequence" int4,
  "parent_path" varchar(255) COLLATE "pg_catalog"."default",
  "img_menu" varchar(255) COLLATE "pg_catalog"."default",
  "action_link" varchar(255) COLLATE "pg_catalog"."default",
  "status" bool DEFAULT true,
  "created_by" varchar(255) COLLATE "pg_catalog"."default",
  "created_dt" timestamp(6),
  "updated_by" varchar(255) COLLATE "pg_catalog"."default",
  "updated_dt" timestamp(6)
)
;

-- ----------------------------
-- Records of tblmenus
-- ----------------------------
INSERT INTO "public"."tblmenus" VALUES (1, 'settings', NULL, 100, NULL, 'icon_settings', '/settings', 't', NULL, '2022-11-18 14:01:20.268313', NULL, NULL);
INSERT INTO "public"."tblmenus" VALUES (2, 'Example', NULL, 1, NULL, NULL, '/example', 't', NULL, '2022-11-18 14:09:26.958027', NULL, NULL);

-- ----------------------------
-- Table structure for tblusers
-- ----------------------------
DROP TABLE IF EXISTS "public"."tblusers";
CREATE TABLE "public"."tblusers" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "username" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "password" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "display_name" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "status" bool NOT NULL DEFAULT true,
  "created_by" varchar(255) COLLATE "pg_catalog"."default",
  "created_dt" timestamp(6),
  "updated_by" varchar COLLATE "pg_catalog"."default",
  "updated_dt" timestamp(6),
  "img_profile" varchar(255) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Records of tblusers
-- ----------------------------
INSERT INTO "public"."tblusers" VALUES (1, 'yayat', 'pbkdf2:sha256:260000$OqgUZ8EPsQtVrrQo$8acabc32efdb76fc6c1beb972d06bb8323ed5ea8ecb94ce33f5752f148d79144', 'Yayat Suyatna', 't', NULL, '2022-11-18 13:50:03.374596', NULL, NULL, NULL);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."tblmenus_id_seq"
OWNED BY "public"."tblmenus"."id";
SELECT setval('"public"."tblmenus_id_seq"', 3, true);
ALTER SEQUENCE "public"."tblusers_id_seq"
OWNED BY "public"."tblusers"."id";
SELECT setval('"public"."tblusers_id_seq"', 2, true);

-- ----------------------------
-- Primary Key structure for table rel_user_menu
-- ----------------------------
ALTER TABLE "public"."rel_user_menu" ADD CONSTRAINT "rel_user_menu_pkey" PRIMARY KEY ("id_user", "id_menu");

-- ----------------------------
-- Primary Key structure for table tblmenus
-- ----------------------------
ALTER TABLE "public"."tblmenus" ADD CONSTRAINT "tblmenus_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table tblusers
-- ----------------------------
ALTER TABLE "public"."tblusers" ADD CONSTRAINT "tblusers_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Foreign Keys structure for table rel_user_menu
-- ----------------------------
ALTER TABLE "public"."rel_user_menu" ADD CONSTRAINT "id_menu" FOREIGN KEY ("id_menu") REFERENCES "public"."tblmenus" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE "public"."rel_user_menu" ADD CONSTRAINT "id_user" FOREIGN KEY ("id_user") REFERENCES "public"."tblusers" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;
